# Generated by Django 4.2.3 on 2023-11-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='unique_date_client',
        ),
    ]
