# Generated by Django 4.2.3 on 2023-11-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_sale_unique_date_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
    ]
