# Generated by Django 4.2.3 on 2023-11-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_price_object'),
        ('transactions', '0004_alter_purchase_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20)),
                ('object', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.object', verbose_name='object')),
                ('purchase', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.purchase', verbose_name='purchase')),
            ],
        ),
    ]
