# Generated by Django 4.2.3 on 2023-11-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_purchase_object_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
