default:
  ENGINE: django.db.backends.mysql
  NAME: ERPdb
  USER: root
  PASSWORD: 
  HOST: localhost
  PORT: 3306
  OPTIONS:
    charset: utf8
    sql_mode: traditional
    unix_socket: /tmp/mysql.sock
