default:
  LINK: http://www.inteligerp.com/ # http://localhost:3000/
  ENGINE: django.db.backends.mysql
  NAME: ERPdb
  USER: root
  PASSWORD: '123456789'
  HOST: localhost
  PORT: 3306
  OPTIONS:
    charset: utf8
    sql_mode: traditional
    unix_socket:
