# Generated by Django 4.2.3 on 2023-08-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_alter_client_cuil_alter_supplier_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CUIL',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='CUIT',
            field=models.CharField(max_length=11),
        ),
    ]
