# Generated by Django 4.2.3 on 2023-11-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_alter_client_cuil_alter_supplier_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CUIL',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='CUIT',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
