# Generated by Django 4.2.3 on 2023-11-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id_warehouse',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
