# Generated by Django 4.2.3 on 2023-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_section_id_warehouse_section_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='length',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='max_weight',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
