# Generated by Django 4.2.3 on 2023-11-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_section_height_alter_section_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='available_storage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
