# Generated by Django 4.2.3 on 2023-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
