# Generated by Django 4.2.3 on 2023-11-03 01:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_object_section_object_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(max_length=50)),
                ('object', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.object', verbose_name='the object that corresponds to the price')),
            ],
        ),
    ]
