# Generated by Django 4.2.3 on 2023-11-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_object_supplier_price_supplier'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('id', 'date'), name='unique_date_id'),
        ),
    ]
