# Generated by Django 4.2.3 on 2023-11-03 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_price_unique_date_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
