# Generated by Django 4.2.3 on 2023-11-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_price_unique_date_id1_price_unique_date_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.object', verbose_name='object'),
        ),
    ]
