# Generated by Django 4.2.3 on 2023-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_object_discontinued'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
