# Generated by Django 4.2.3 on 2023-12-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_object_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='product_id',
        ),
    ]
